### ISSUE TITLE
how can i run  gulp?

### ISSUE THREAD

**Issue by ashokgaire** [lllychen/jekyll-firewall#8]
i can not directly run glupfile..
fs.js:36
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:36:5
    at req_ (/home/oxy/Personal_website/mysite/jekyll-password-protect/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/home/oxy/Personal_website/mysite/jekyll-password-protect/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/home/oxy/Personal_website/mysite/jekyll-password-protect/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)

**Comment by ashokgaire** [comment]
its fixed now .. something to do with  npm version..
